	//constants.ts
export const AFTER_EVENTS = [
    'blockExplode'
    , 'buttonPush'
    , 'chatSend'
    , 'dataDrivenEntityTrigger'
    , 'effectAdd'
    , 'entityDie'
    , 'entityHealthChanged'
    , 'entityHitBlock'
    , 'entityHitEntity'
    , 'entityHurt'
    , 'entityLoad'
    , 'entityRemove'
    , 'entitySpawn'
    , 'explosion'
    , 'gameRuleChange'
    , 'itemCompleteUse'
    , 'itemReleaseUse'
    , 'itemStartUse'
    , 'itemStartUseOn'
    , 'itemStopUse'
    , 'itemStopUseOn'
    , 'itemUse'
    , 'itemUseOn'
    , 'leverAction'
    , 'messageReceive'
    , 'pistonActivate'
    , 'playerBreakBlock'
    , 'playerDimensionChange'
    , 'playerEmote'
    , 'playerGameModeChange'
    , 'playerInputPermissionCategoryChange'
    , 'playerInteractWithBlock'
    , 'playerInteractWithEntity'
    , 'playerJoin'
    , 'playerLeave'
    , 'playerPlaceBlock'
    , 'playerSpawn'
    , 'pressurePlatePop'
    , 'pressurePlatePush'
    , 'projectileHitBlock'
    , 'projectileHitEntity'
    , 'targetBlockHit'
    , 'tripWireTrip'
    , 'weatherChange'
    , 'worldInitialize'

]

export const BEFORE_EVENTS = [
    'chatSend'
    , 'effectAdd'
    , 'entityRemove'
    , 'explosion'
    , 'itemUse'
    , 'itemUseOn'
    , 'playerBreakBlock'
    , 'playerGameModeChange'
    , 'playerInteractWithBlock'
    , 'playerInteractWithEntity'
    , 'playerLeave'
    , 'playerPlaceBlock'
    , 'weatherChange'
    , 'worldInitialize'
];
